version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-scan:
          context:
            - semgrep
jobs:
  semgrep-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: |
              export SEMGREP_APP_TOKEN=$SEMGREP_APP_TOKEN
              export SEMGREP_COMMIT=$CIRCLE_SHA1
              export SEMGREP_JOB_URL=$CIRCLE_BUILD_URL
              PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | awk -F '/' '{print $NF}' )
              if [ -n "$CIRCLE_PULL_REQUEST" ]; then
                  echo 'export SEMGREP_BASELINE_REF = "origin/<< pipeline.parameters.master_branch >>"' >> $BASH_ENV
                  echo "Pull Request Number: $PR_NUMBER"
                  echo 'export SEMGREP_PR_ID=$PR_NUMBER' >> $BASH_ENV
                  git fetch origin "+refs/heads/*:refs/remotes/origin/*"
                  semgrep ci --baseline-commit=$(git merge-base development HEAD)
              else
                  if [ "$CIRCLE_BRANCH" == "development" ]; then
                      echo "Running Full scan for branch: $CIRCLE_BRANCH"
                      semgrep ci || true
                  else
                      echo "Skipping full scan for branches different to development"
                  fi
              fi

