version: 2.1

jobs:
  semgrep-scan:
    docker:
      - image: semgrep/semgrep
    parameters:
      service:
        type: string
    steps:
      - checkout
      - run:
          name: Set script permissions
          command: chmod +x .circleci/base_config/semgrep.sh
      - run:
          name: "Semgrep scan"
          command: |
              echo "Service parameter value is << parameters.service >>"
              .circleci/base_config/semgrep.sh

workflows:
  semgrep:
    jobs:
      - semgrep-scan:
          name: semgrep-scan
          service: "<< pipeline.parameters.service >>"
          context:
            - semgrep
