version: 2
jobs:
  semgrep-scan:
    docker:
      - image: semgrep/semgrep
    environment:
      BRANCH_NAME: ${CIRCLE_BRANCH}
    steps:
      - checkout
      - run:
          name: Mask Branch Name
          command: |
            echo "Setting branch name..."
            echo "export BRANCH_NAME=${CIRCLE_BRANCH}" >> $BASH_ENV
      - run:
          name: "Semgrep scan"
          command: |
            .circleci/base_config/semgrep.sh

workflows:
  version: 2
  semgrep:
    jobs:
      - semgrep-scan
