
version: 2
jobs:
  semgrep-scan:
    context:
      - semgrep
    docker:
      - image: semgrep/semgrep
    environment:
      BRANCH_NAME: ${CIRCLE_BRANCH}
    steps:
      - checkout
      - run:
          name: Set script permissions
          command: chmod +x .circleci/base_config/semgrep.sh
      - run:
          name: "Semgrep scan"
          command: |
              .circleci/base_config/semgrep.sh
workflows:
  version: 2
  semgrep:
    jobs:
      - semgrep-scan:
          context:
            - semgrep

