version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-scan:
          context:
            - semgrep

jobs:
  semgrep-scan:
    docker:
      - image: semgrep/semgrep
    environment:
    # Setting the branch name as an environment variable
      BRANCH_NAME: << pipeline.git.branch >>
    steps:
      - checkout
      - run:
          name: Mask Branch Name
          command: |
            echo "Setting branch name..."
            echo "export BRANCH_NAME=${BRANCH_NAME}" >> $BASH_ENV
      - run:
          name: "Semgrep scan"
          command: |
              .circleci/base_config/semgrep.sh
             
