
version: 2

parameters:
  service:
    type: string
    default: "A"

jobs:
  semgrep-scan:
    parameters:
      service:
        type: string
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run:
          name: Set script permissions
          command: chmod +x .circleci/base_config/semgrep.sh
      - run:
          name: "Semgrep scan"
          command: |
              echo "Service parameter value is << parameters.service >>"
              .circleci/base_config/semgrep.sh
workflows:
  version: 2
  semgrep:
    jobs:
      - semgrep-scan:
          service: "<< pipeline.parameters.service >>"
          context:
            - semgrep

